cleaned up BE
AnnaMikarey/LoanCalculator pull request #6
Opened 2023-04-18 06:06 UTC by Lymetta

Did the code refactoring according to mentor's recommendations. Please check if I missed anything. I used Big Decimal for calculation results only (I doubt user or admin will send big decimal type input), didn't add @Qualifier (still discussing with mentor, will update if anything changes).

2023-04-18 06:53 UTC, AudriusAnusauskas reviewed
I think everything seems fine, changed the way agreed yesterday. At least I did not find anything missing.
The naming of the data fields should be agreed. As I see you have classes for AdminData and CalculatorData. And fields that are in common for admin you simply add 'admin' in the beginning of each field name. And that is a good idea. So I think there should be a consistency in naming. Like if you have 'euriborInterestRate' and 'adminEuriborInterest' I think they should be similar, just with and without prefix 'admin'. Also with min, max and default 'price' in admin and 'value' in calculator. I think they should be same, just difference in prefix.
Just my thoughts :)

2023-04-18 11:27 UTC, Rytautas requested changes

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/controllers/AdminController.java
> +@RequestMapping("admin")
i would suggest putting '/' before the endpoint name. i.e. @ RequestMapping("/admin")

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/controllers/AdminController.java
> +    @GetMapping("values")
same as above, but also make the endpoint name more meaningful like "/get-values"

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/controllers/CalculatorController.java
> +package com.server.loan.calculator.controllers;
package name should be singular - controller

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/controllers/CalculatorController.java
>      @GetMapping
add a meaningful name to this endpoint, like "calculate-mortgage"

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/errors/ErrorMessage.java
> +package com.server.loan.calculator.errors;
package name should be singular - error

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/services/AdminService.java
> +    private void validateAdminInput () {
would make more sense to move this validation to a separate validator class like DataValidator

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/services/CalculatorService.java
> +package com.server.loan.calculator.services;
package name should be singular - service

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/services/CalculatorService.java
> +@Data
service should not have @ Data annotation

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/services/CalculatorService.java
> +    private final CalculatorData data;
should not be auto injected, later you will instantiate this class through endpoint controller or database DAO, so in this case you should just do new CalculatorData()

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/models/AdminData.java
> +    private double adminEuriborInterest = 3.31;
all money related variables should be BigDecimal

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/models/CalculatorData.java
> +    private double euriborInterestRate = 3.31;
all money related variables should be BigDecimal

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/services/CalculatorService.java
> +        inputValidator.validate(data.getSalary());
all this validation should be moved to a separate class, and should be called before calling calculation methods

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/services/CalculatorService.java
> +        valueInRangeValidator.validate(data.getPropertyValue(), data.getMinPropertyValue(), data.getMaxPropertyValue());
all this validation should be moved to a separate class, and should be called before calling calculation methods

2023-04-18 11:27 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/validators/InputAsCorrectNumberValidator.java
> +package com.server.loan.calculator.validators;
package name should be singular - validator

2023-04-18 11:27 UTC, Rytautas commented on server/src/test/java/com/server/loan/LoanCalculatorApplicationTests.java
> +package com.server.loan;
should be moved to com.server.loan.calculator

2023-04-19 12:20 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/service/AdminService.java
> +    private final AdminData adminData = new AdminData();
would make more sense to instantiate this inside the method that you are using to return it, as later you will be getting it from database

2023-04-19 12:28 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/validator/AdminDataValidator.java
> +    private final AdminData adminData;
should not be here as a field. methods that use/validate data should take it as a parameter

2023-04-19 12:29 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/validator/AdminDataValidator.java
> +    private final BigDecimalValueInRangeValidator valueInRangeValidator = new BigDecimalValueInRangeValidator();
with @ RequiredArgsConstructor annotation you dont need to instantiate these classes, if they are annotated with @ Component or @ Service annotations, which they should be

2023-04-19 12:29 UTC, Rytautas commented on server/src/main/java/com/server/loan/calculator/validator/AdminDataValidator.java
> +    private final BigDecimalInputAsCorrectNumberValidator inputValidator = new BigDecimalInputAsCorrectNumberValidator();
with @ RequiredArgsConstructor annotation you dont need to instantiate these classes, if they are annotated with @ Component or @ Service annotations, which they should be

2023-04-20 05:42 UTC, merged